name = "Cozy Create"
author = "Kavikick"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d940df0ec8d50f0ae6c3870469fdb701e24a1e3cbfed06c93a82c098aff39e35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
