name = "Cozy Create"
author = "Kavikick"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24184ce992fa4fc5f354e157790828fb47cf9d08208b6e1090fb65803fd64fef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
