name = "Cozy Create"
author = "Kavikick"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db0aafad65eb916457639bee2175e8cc7845c434c541d5c28a3844ca01f77666"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
